# conda create --name cap --clone cap
# conda env create -n cap --file environment.yml --force
# conda env update -n cap --file environment.yml --prune
# conda env remove -n cap
name: cap
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - git
  - requests
  - jupyterlab
  - ipywidgets
  - tqdm
  - pyyaml
  - matplotlib
  - pandas
  - scikit-image
  - pillow
  - pip:
    - tensorboard

